// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJx8KNpt_NUp9qaSSHdipKH2dx2Dx2Ido',
    appId: '1:722736563548:web:24e2d85a67236483c32d99',
    messagingSenderId: '722736563548',
    projectId: 'crossclip-c93e2',
    authDomain: 'crossclip-c93e2.firebaseapp.com',
    storageBucket: 'crossclip-c93e2.firebasestorage.app',
    measurementId: 'G-604N5BER3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAC_EFjrGAxE1pNmDuaLjaTjUuseFZcI4',
    appId: '1:722736563548:android:4c83176bdc9dc359c32d99',
    messagingSenderId: '722736563548',
    projectId: 'crossclip-c93e2',
    storageBucket: 'crossclip-c93e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuuCy6_rWMx3IlEu-kwl4q30oU4x7Twrs',
    appId: '1:722736563548:ios:ccc7721ba4861308c32d99',
    messagingSenderId: '722736563548',
    projectId: 'crossclip-c93e2',
    storageBucket: 'crossclip-c93e2.firebasestorage.app',
    iosBundleId: 'com.example.crosslipFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuuCy6_rWMx3IlEu-kwl4q30oU4x7Twrs',
    appId: '1:722736563548:ios:ccc7721ba4861308c32d99',
    messagingSenderId: '722736563548',
    projectId: 'crossclip-c93e2',
    storageBucket: 'crossclip-c93e2.firebasestorage.app',
    iosBundleId: 'com.example.crosslipFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJx8KNpt_NUp9qaSSHdipKH2dx2Dx2Ido',
    appId: '1:722736563548:web:790d53afb48f24e9c32d99',
    messagingSenderId: '722736563548',
    projectId: 'crossclip-c93e2',
    authDomain: 'crossclip-c93e2.firebaseapp.com',
    storageBucket: 'crossclip-c93e2.firebasestorage.app',
    measurementId: 'G-GSNYBDC0F0',
  );
}
